# Generated by Django 3.1.1 on 2020-10-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owaspflawsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='Log',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='Recipe',
        ),
    ]
